### ISSUE TITLE
Document our various CI Processes

### ISSUE THREAD

**Issue by Rosuavio** [CommunityToolkit/WindowsCommunityToolkit-wiki#2]
We have a fair amount of code present primarily to run as part of the CI pipeline. Documentation on how this code works as well on how to use it could serve to help contributors in using and improving the CI pipeline.

Some key things to document.
- How the CI pipeline is triggered and configured.
- The Cake build tool.
- ~~The headers situation~~
- The `build/build.ps1` script.
- All the commands to invoke particular parts of the CI pipeline.
  - Tests/checks
  - build steps
- How to add to the CI pipeline.

**Comment by michael-hawker** [comment]
We should add how our smoke tests work see https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/3448#issuecomment-724925315

Including how to grab stats on artifact size from published artifacts:
https://dev.azure.com/dotnet/WindowsCommunityToolkit/_build/results?buildId=41520&view=artifacts&type=publishedArtifacts
